# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hood',
            old_name='description',
            new_name='population',
        ),
        migrations.RemoveField(
            model_name='hood',
            name='admin',
        ),
    ]
