# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 04:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0002_auto_20190327_0645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='cartefory',
            new_name='cartegory',
        ),
    ]
