# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0003_auto_20190327_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='profile',
        ),
    ]
