# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0005_auto_20190325_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cartefory', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='Businessimage/')),
                ('description', models.CharField(max_length=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='neighbourhood.Profile')),
            ],
        ),
    ]
